### ISSUE TITLE
Use versions.yaml to fetch helm API fields

### ISSUE THREAD

**Issue by dgn** [istio-ecosystem/sail-operator#195]
We're currently hard-coding commit hashes of the istio/istio and istio/api repositories in the Makefile.core.mk, which are used to fetch API specs which we generate our CRDs from. We should use the `crdSourceVersion` field we have in versions.yaml to determine which version defines the set of fields we want to include.

**Comment by luksa** [comment]
We removed the hard-coded commit hashes a while ago. Instead, we're now using the version specified in go.mod to generate the API schema. Also, in #318, we're also making sure that the Istio CRDs are pulled from the same go.mod version and removing the `crdSourceVersion` field.
