### ISSUE TITLE
Review ExtensionProvider structs

### ISSUE THREAD

**Issue by dgn** [istio-ecosystem/sail-operator#256]
We need to make sure that our transformer script copies all fields from the ExtensionProvider structs, as they make heavy use of protobuf oneofs, which could lead to errors. One thing we already know is missing is the Sampling field in the OpenTelemetry provider.

**Comment by bmangoen** [comment]
It looks like the field [`Sampling`](https://github.com/istio/api/blob/master/mesh/v1alpha1/config.pb.go#L3905) is actually named  `dynatraceSampler` (cf. [Mesh Config API reference](https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/#MeshConfig-ExtensionProvider-OpenTelemetryTracingProvider)). The type `*MeshConfigExtensionProviderOpenTelemetryTracingProviderDynatraceSampler` is also correct as it is defined in the Mesh [config.pb.go](https://github.com/istio/api/blob/master/mesh/v1alpha1/config.pb.go#L3989-L4018)

**Comment by luksa** [comment]
Yes, the `sampling` field is not really missing. If you check the field definition in the upstream [config.pb.go](https://github.com/istio/api/blob/5536f055d8e5a120a9c28eb482daa9d9c8682b9f/mesh/v1alpha1/config.pb.go#L3905) file, you'll notice that the field doesn't have any `json` tags, but the other fields do. This means that in json/yaml, the field is collapsed, meaning that the fields in the type are added directly to the grandparent type, skipping the parent (the field in question). 

You can also see that this is the case by looking at the documentation. Look for the `dynatraceSampler` field in this [table](https://github.com/istio/api/blob/5536f055d8e5a120a9c28eb482daa9d9c8682b9f/mesh/v1alpha1/config.pb.go#L3905). There is no `sampling` field. 

This is how oneof fields are implemented across the entire Istio API. For example, the same pattern can be found in `MeshConfig_ExtensionProvider`. In the config.pb.go file, the `MeshConfig_ExtensionProvider` struct contains a single field called [Provider](https://github.com/istio/api/blob/5536f055d8e5a120a9c28eb482daa9d9c8682b9f/mesh/v1alpha1/config.pb.go#L1981), which is a oneof. In YAML, there is no such field. Instead, the `MeshConfig_ExtensionProvider` type contains all all the fields from all the extensionProvider types. You can see this in [this table](https://github.com/istio/api/blob/5536f055d8e5a120a9c28eb482daa9d9c8682b9f/mesh/v1alpha1/config.pb.go#L1981).

So, the API is exactly as it should be.
