### ISSUE TITLE
Add Readme for the operator helm chart

### ISSUE THREAD

**Issue by FilipB** [istio-ecosystem/sail-operator#314]
### Is this the right place to submit this?

- [X] This is not a question about how to use the sail-operator

### Feature Description

We are publishing our operator helm chart but it's missing a Readme.
It should contain information how to install on K8s and OCP.

**Comment by MaxBab** [comment]
Hi @FilipB 

Are we publishing the sail-operator help charts to some place?
I haven't found it on ArtifactHub.

Or should I define charts deployment from the repository in a readme file?

Thanks.

**Comment by FilipB** [comment]
Currently it's only published as a part of GH [release](https://github.com/istio-ecosystem/sail-operator/releases/tag/0.1.0-rc.1). I'm not sure what's the plan with ArtifactHub, let's discuss on next team call.
