### ISSUE TITLE
Complete Community Standards checklist

### ISSUE THREAD

**Issue by fjglira** [istio-ecosystem/sail-operator#361]
To complete the Community Standards [checklist](https://github.com/istio-ecosystem/sail-operator/community), we need to add 2 items to our project:

- [X] Code of conduct - https://github.com/istio-ecosystem/sail-operator/pull/362
- [x] Pull request template - https://github.com/istio-ecosystem/sail-operator/pull/366

With this, we will meet the Opensource community standards

**Comment by fjglira** [comment]
Hey @pbajjuri20 this is a good first issue to start to be familiar with the repository

**Comment by MaxBab** [comment]
I'll take it, if that's ok.

**Comment by fjglira** [comment]
Ok for me

**Comment by pbajjuri20** [comment]
@MaxBab: I will also, learn with you about this issue.

**Comment by pbajjuri20** [comment]
https://docs.google.com/document/d/1BhR82y2-g4iHgW5H_rTfcXfb2KqaM5llH5mLRAC1deU/edit. 

Here, I'm, adding for the Code of conduct
