### ISSUE TITLE
[BUG] Latest Istio version can't be deployed using the operator on OCP clusters

### ISSUE THREAD

**Issue by fjglira** [istio-ecosystem/sail-operator#382]
### Is this the right place to submit this?

- [X] This is not a question about how to use the sail-operator

### Bug Description

Since `profiles` was [changed](https://github.com/istio/istio/pull/52981) upstream few weeks ago we can't deploy the latest Istio version on OCP cluster because we use `profile=openshift` in the [operator](https://github.com/istio-ecosystem/sail-operator/blob/bd6e0482446decb56d55a7344296a29408dee4b4/bundle/manifests/sailoperator.clusterserviceversion.yaml#L666) to set everything to be able to run on OCP cluster. If we try to deploy a Istio or IstioCNI resource we are going to get this error:
`failed to install helm chart cni: execution error at (cni/templates/zzz_profile.yaml:26:3):unknown profile openshift`

### Operator Version

master branch

**Comment by luksa** [comment]
Will be fixed by https://github.com/istio/istio/pull/53574

**Comment by luksa** [comment]
This is now fixed.
