### ISSUE TITLE
[BUG] Latest helm chart version not aligned with default image.

### ISSUE THREAD

**Issue by twhite0** [istio-ecosystem/sail-operator#420]
### Is this the right place to submit this?

- [X] This is not a question about how to use the sail-operator

### Bug Description

0.2-latest and 0.2-nightly-2024-10-14 in quay.io/maistra-dev are still generated with `/manager` as the operator name.  [This](https://github.com/istio-ecosystem/sail-operator/commit/3656ec9be7edb0f93c8ec12cfefed985950c13b2) commit updated the operator name and helm chart command.  

Temporary fix is to edit the Deployment chart and revert to using /manager as the command

### Operator Version

0.2-latest

### Additional Information

```
  Warning  Failed          65s                 kubelet            Error: container create failed: time="2024-10-14T23:06:28Z" level=error msg="runc create failed: unable to start container process: exec: \"/sail-operator\": stat /sail-operator: no such file or directory"
```

**Comment by dgn** [comment]
interesting. did you use the charts from `main` to install the `0.2-latest` image? if so, this should be fixed within a day or so.. we currently build the nightly images from another repo that is synced automatically, but it has a slight delay

**Comment by luksa** [comment]
The [sync PR](https://github.com/openshift-service-mesh/sail-operator/pull/141) is currently broken because tests fail. See https://github.com/istio-ecosystem/sail-operator/issues/382.

A fix is on the way: https://github.com/istio/istio/pull/53574.

**Comment by twhite0** [comment]
0.2-latest has the updated command (`sail-operator`)
