### ISSUE TITLE
[FEATURE] Avoid the use of bookinfo as testing app or enable a way to set custom images

### ISSUE THREAD

**Issue by fjglira** [istio-ecosystem/sail-operator#467]
### Is this the right place to submit this?

- [X] This is not a question about how to use the sail-operator

### Feature Description

We can test the configuration in the e2e framework by using an alternative containers or adding the possibility to set custom images that can be set by the user to avoid pulling always upstream images to run the test

**Comment by fjglira** [comment]
Checking the code we use bookinfo app only to validate istio injection, we can change this and use any other app that can allow us to check this and also that can work later as tooling app to validate connection when we is needed, in multicluster test we use sample and sleep app. @FilipB I think I can set a way to set a custom image for those containers and continuing using sleep pod or sample app because we will need this types of apps to validate connectivity in diferents scenarios later. WDYT?

**Comment by FilipB** [comment]
I don't know if we will need to use the sleep app for e2e operator tests in the future. If yes, let's use it. If no, we could test the injection just using a standalone ingress

**Comment by fjglira** [comment]
I'll work on this next week. Folks from IBM needed to be able to set their own images, this will leave to the user the possibility to set their own container image for the test run
