### ISSUE TITLE
Prepare 0.1 release

### ISSUE THREAD

**Issue by dgn** [istio-ecosystem/sail-operator#90]
- [x] Create release branch
      Branch off `main`
      We don’t want to create the branch too early before a release to avoid a lot of cherrypicks from the main branch
- [X] Increment the minor version on the main branch
- [X] Create prow jobs for new branch
      Example PR for test-infra [repo](https://github.com/istio/test-infra/pull/5399)
- [x] Create cherry-pick label for new branch (e.g. cherrypick/release-0.1)
- [X] Update versions.yaml to contain only expected versions
- [X] Update common-files to point to latest supported Istio release branch
      Common-files can be updated via setting [`UPDATE_BRANCH`](https://github.com/istio-ecosystem/sail-operator/blob/release-0.1/Makefile.core.mk#L22) in the Makefile.core.md and running `make update-common`
- [X] Update dependencies to point to latest supported Istio release branch
      Dependencies can be updated via [`update_deps.sh`](https://github.com/istio-ecosystem/sail-operator/blob/324dcbc08858b1e4d65f4ae737ab824fac15d802/tools/update_deps.sh#L19) with correct `UPDATE_BRANCH` variable.
- [x] Check used versions in `go.mod`
     `update_deps.sh` updates modules in `go.mod` to the latest versions in `UPDATE_BRANCH` so it might not be the versions used in actual istio release. Ideally we should use the actual release tag in `go.mod`. For example `istio.io/client-go v1.23.0` instead of e.g. `istio.io/client-go v1.23.0-alpha.0.0.20240809192551-f32a7326ae19`. This is not possible for `istio.io/istio` as the version tags don't contain the `v` prefix, so for that repository we'll have to use the pseudoversion. This can be done e.g. `go get -u istio.io/istio@1.23.0`

**Comment by fjglira** [comment]
Prow jobs were created here: https://github.com/istio/test-infra/pull/5399 by Filip
The branch is already created: https://github.com/istio-ecosystem/sail-operator/tree/release-0.1

I think we can close the issue
